# access tokens with different roles
@customer = {{bpp-dashboard/token/qolari_PARTNER/customer}}
@driver = {{bpp-dashboard/token/qolari_PARTNER/driver}}
@Qolari_ops = {{bpp-dashboard/token/qolari_PARTNER/Qolari_ops}}
@Qolari_admin = {{bpp-dashboard/token/qolari_PARTNER/Qolari_admin}}
@customer_service = {{bpp-dashboard/token/qolari_PARTNER/customer_service}}

# @name healthcheck
GET {{bpp-dashboard-host}}

###

# @name operatorRegistration

POST {{bpp-dashboard-host}}/bpp/driver-offer/qolari_PARTNER/KOCHI/operator/register
token: {{Qolari_admin}}
content-type: application/json

{
    "firstName": "John",
    "lastName": "Smith",
    "mobileNumber": "2212345678",
    "mobileCountryCode": "+91",
    "email": "operator@drive.qolari.com"
}

###

# @name operatorLogin

POST {{bpp-dashboard-host}}/fleet/login/otp
content-type: application/json

  { "mobileNumber": "2212345678",
    "mobileCountryCode": "+91",
    "merchantId": "qolari_PARTNER",
    "city": "Kochi"
  }

###

# @name operatorVerify

POST {{bpp-dashboard-host}}/fleet/verify/otp
content-type: application/json

  { "mobileNumber": "2212345678",
    "mobileCountryCode": "+91",
    "merchantId": "qolari_PARTNER",
    "city": "Kochi",
    "otp": "7891"
  }
