# access tokens with different roles
@customer = {{bpp-dashboard/token/qolari_PARTNER/customer}}
@driver = {{bpp-dashboard/token/qolari_PARTNER/driver}}
@Qolari_ops = {{bpp-dashboard/token/qolari_PARTNER/Qolari_ops}}
@Qolari_admin = {{bpp-dashboard/token/qolari_PARTNER/Qolari_admin}}
@customer_service = {{bpp-dashboard/token/qolari_PARTNER/customer_service}}

# @name healthcheck
GET {{bpp-dashboard-host}}

###

# @name getOnboardingDocumentConfigs

GET {{bpp-dashboard-host}}/bpp/driver-offer/qolari_PARTNER/KOCHI/onboarding/document/configs
token: {{Qolari_admin}}

###

# @name getOnboardingRegisterStatus

# INSERT INTO atlas_bpp_dashboard.fleet_member_association (fleet_member_id, fleet_owner_id, enabled, is_fleet_owner) VALUES
#   ('3680f4b5-dce4-4d03-aa8c-5405690e87bd', 'favorit-fleet-owner-0000000000000000', true, true);

GET {{bpp-dashboard-host}}/bpp/driver-offer/qolari_PARTNER/KOCHI/onboarding/register/status?driverId=favorit-auto2-0000000000000000000000&onlyMandatoryDocs=true
token: {{Qolari_admin}}
