@token2 = {{driver-offer-bpp-auto-token2}}
@driver-offer-bpp-host = http://localhost:8016
@Qolari_admin = {{bpp-dashboard/token/qolari_PARTNER/Qolari_admin}}

# @name healthcheck
GET {{driver-offer-bpp-host}}/ui

###

# @name getInvoice

GET {{driver-offer-bpp-host}}/ui/invoice
content-type: application/json
token: {{Qolari_admin}}

