[program:qolari-horizon]
process_name=%(program_name)s
command=php /var/www/qolari/current/artisan horizon
directory=/var/www/qolari/current
user=qolari
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/www/qolari/shared/storage/logs/horizon.log
stopwaitsecs=3600
