# access tokens with different roles
@customer = {{bpp-dashboard/token/qolari_PARTNER/customer}}
@driver = {{bpp-dashboard/token/qolari_PARTNER/driver}}
@Qolari_ops = {{bpp-dashboard/token/qolari_PARTNER/Qolari_ops}}
@Qolari_admin = {{bpp-dashboard/token/qolari_PARTNER/Qolari_admin}}
@customer_service = {{bpp-dashboard/token/qolari_PARTNER/customer_service}}

# @name healthcheck
GET {{bpp-dashboard-host}}

###

# @name CurrentActiveRideAPI

@vehicleNumber = auto1-0000000000000000000000

GET {{bpp-dashboard-host}}/bpp/driver-offer/qolari_PARTNER/KOCHI/ride/{{vehicleNumber}}/currentActiveRide
token: {{Qolari_admin}}
content-type: application/json

